workflows:
  ios-basic:
    name: iOS Basic Build
    environment:
      xcode: latest
    scripts:
      - name: Build TraccarManager
        script: |
          xcodebuild -project TraccarManager.xcodeproj \
                     -scheme TraccarManager \
                     -sdk iphoneos \
                     -configuration Release \
                     build
    artifacts:
      - build/**/*.app
